### ISSUE TITLE
Issue with Fabric and Python 3.4 on a Mac

### ISSUE THREAD

**Issue by springcoil** [andreasjansson/simple-aws-gpu-setup#4]
usr/bin/python: No module named virtualenvwrapper
virtualenvwrapper.sh: There was a problem running the initialization hooks.

If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python and that PATH is
set properly.
Peadars-MBP% fab
Traceback (most recent call last):
  File "/Users/peadarcoyle/anaconda/bin/fab", line 9, in <module>
    load_entry_point('Fabric==1.10.2', 'console_scripts', 'fab')()
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/**init**.py", line 552, in load_entry_point
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/**init**.py", line 2672, in load_entry_point
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/**init**.py", line 2345, in load
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/**init**.py", line 2351, in resolve
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/fabric/main.py", line 12, in <module>
    from operator import isMappingType
ImportError: cannot import name 'isMappingType'
Peadars-MBP% fab pricing
Traceback (most recent call last):
  File "/Users/peadarcoyle/anaconda/bin/fab", line 9, in <module>
    load_entry_point('Fabric==1.10.2', 'console_scripts', 'fab')()
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/**init**.py", line 552, in load_entry_point
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/**init**.py", line 2672, in load_entry_point
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/**init**.py", line 2345, in load
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/**init**.py", line 2351, in resolve
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/fabric/main.py", line 12, in <module>
    from operator import isMappingType
ImportError: cannot import name 'isMappingType'

**Comment by andreasjansson** [comment]
Looks like this is an issue with Python 3 and the version of fabric headintheclouds depends on: https://github.com/fabric/fabric/issues/1017

If you're brave you could try upgrading to a different version of fabric, but I have no guarantees that anything will work. I'd probably just stick with Python 2.7 for now.

**Comment by springcoil** [comment]
Agreed

On Tuesday, 21 July 2015, Andreas Jansson notifications@github.com wrote:

> Looks like this is an issue with Python 3 and the version of fabric
> headintheclouds depends on: fabric/fabric#1017
> https://github.com/fabric/fabric/issues/1017
> 
> If you're brave you could try upgrading to a different version of fabric,
> but I have no guarantees that anything will work. I'd probably just stick
> with Python 2.7 for now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreasjansson/simple-aws-gpu-setup/issues/4#issuecomment-123126576
> .

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com
